import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {FaPaintBrush} from "react-icons/fa"
import {FaShapes} from "react-icons/fa"
import {FaHeadset} from "react-icons/fa"
import {BsFillPlayCircleFill} from "react-icons/bs"
import Navbar from './component/Navbar'
import Footer from './component/Footer'



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Business App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="All">
        <img src="/img.jpg" alt="Loading..." className='absolute w-full h-4/5 object-cover cover center'/>
        <div className="cov relative">
          <div className="">
            <Navbar />
          </div>
          <div className="top">
            <h1 className='text-white text-5xl font-bold text-center mt-32 tracking-wide MT'>The best Products <br /> <span className='mt-4'> start with Figma</span></h1>
            <p className='text-white mt-8 pb-24 text-center text-3xl MD'>Most calendars are designed fior teans. Slate is designed<br />for freelancers</p>
            <div className="pb-20">
            <button className='btm text-2xl bg-blue-500 px-24 py-4 rounded-full block mx-auto text-white font-bold hover:bg-blue-800'>Try For Free</button>
            </div>
          </div>
        </div>
      </div>
        <div className="cont"></div>
        <div className="conts relative">
          <div className="">
            <h1 className='text-center font-medium text-4xl tracking-wide mt-20'>Features</h1>
            <p  className='text-center text-xl tracking-wide mt-6 text-gray-700'>Most calendar are designed for teams <br /> Slate is designed for freelancers</p>
          </div>
          <div className="grid">
            <div className="one my-16">
              <p className='text-blue-600 text-3xl MX'><FaShapes/></p>
              <p className='text-center font-bold text-gray-900 text-2xl mb-6'>OpenType features Varibales fonts</p>
              <p className='text-center'>Slate helps you see how <br />many days you need <br /> to work to reach your <br />financial goal</p>
            </div>
            <div className="two A my-16">
            <p className='text-blue-600 text-3xl MX'><FaPaintBrush/></p>
              <p className='text-center font-bold text-gray-900 text-2xl mb-6'>Design with real data</p>
              <p className='text-center'>Slate helps you see how <br />many days you need <br /> to work to reach your <br />financial goal</p>
            </div>
            <div className="third A my-16">
            <p className='text-blue-600 text-3xl MX'><FaHeadset/></p>
              <p className='text-center font-bold text-gray-900 text-2xl mb-6'>Fastest way to take action</p>
              <p className='text-center'>Slate helps you see how <br />many days you need <br /> to work to reach your <br />financial goal</p>
            </div>
          </div>
          <div className="img2">
            <img src="/img4.jpg" alt="Loading..." className='rounded-3xl shadow-2xl absolute AG'/>
            <div className="play relative px-72 py-40 text-7xl text-blue-600">
              <BsFillPlayCircleFill />
            </div>
          </div>
          <div className="grids BG">
            <div className="my-24">
              <p className='text-3xl font-bold'>Fastest way to <br />organize</p>
              <p className='my-6 font-medium'>Most calendars are designed for teams. <br />Slate is designed for freelancers</p>
              <button className='bg-blue-600 text-white px-16 py-3 rounded-full'>Try For Free</button>
            </div>
            <img src="/img2.jpg" alt="Loading..."/>
          </div>
          <div className="gridy">
            <img src="/img3.jpg" alt="Loading..." className='S'/>
            <div className="mt-10 BG">
              <p className='text-lg font-black'>At your fingertips</p>
              <p className='my-3 font-normal text-4xl'>Lightning fast <br />Prototyping</p>
              <p className='font-black text-lg whitespace-nowrap my-5'>Subscribe to our Newletter <br /> <span className='font-thin'>Available exclusivery on Figmaland</span></p>
              <form className='set'>
                <input type="text" className='BM bg-gray-200 rounded-full px-8' placeholder='Your Email'/>
                <button type='submit' className='bg-blue-600 px-6 py-3 ml-4 text-white rounded-full border-none BH'>Subscribe</button>
              </form>
            </div>
          </div>
          <div className="Q">
            <div className="p">
              <h1 className='text-5xl text-center font-semibold'>Partners</h1>
              <p className='text-xl text-center font-medium my-6'>Most calenders are designed for teams. <br />Slate is designed for freelancers</p>
            </div>
            <div className="display">
              <img src="/1.jpg" alt="Loading..." className='border-current border-2 g shadow-2xl'/>
              <img src="/2.jpg" alt="Loading..." className='border-current border-2 g shadow-2xl'/>
              <img src="/3.jpg" alt="Loading..." className='border-current border-2 g shadow-2xl'/>
              <img src="/4.jpg" alt="Loading..." className='border-current border-2 g shadow-2xl'/>
              <img src="/2.jpg" alt="Loading..." className='border-current border-2 g shadow-2xl'/>
              <img src="/3.jpg" alt="Loading..." className='border-current border-2 g shadow-2xl'/>
              <img src="/4.jpg" alt="Loading..." className='border-current border-2 g shadow-2xl'/>
              <img src="/1.jpg" alt="Loading..." className='border-current border-2 g shadow-2xl'/>   
            </div>
          </div>
          <div className="bt">
            <button type='submit' className='bg-blue-600 px-20 py-3 mx-auto my-8 text-white rounded-full border-none block font-medium'>Try For Free</button>  
          </div>
        </div>
        <div className="testimonies Q">
          <div className="">
            <h1 className='text-5xl text-center font-semibold'>Testimomials</h1>
            <img src="/5.jpg" alt="Loading..." className='w-20 mx-auto m my-12 shadow-2xl'/>
            <p className='text-xl text-center font-normal font'>Most calenders are designed for teams. Slate is designed for freelancers</p>
            <p className='text-xl text-center font-normal font'>Who want a simple way to plan their schedule.</p>
          </div>
          <div className="auto flex">
            <img src="/6.jpg" alt="Loading..." className='AS shadow-2xl'/>
            <p className='ml-4 whitespace-nowrap font-semibold'>Organize across <br /> UI designers </p>
          </div>
          <button type='submit' className='bg-blue-600 px-20 py-3 mx-auto my-8 text-white rounded-full border-none block font-medium'>More Testimonies</button>  
        </div>
        <Footer />
    </div>
  )
}
